"""add is_active, category and author

Revision ID: 80084fc4bb32
Revises: 15f797438ad8
Create Date: 2024-11-28 22:08:10.337105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80084fc4bb32'
down_revision = '15f797438ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Unknown'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'Unknown'"))

    # ### end Alembic commands ###
