"""user model added

Revision ID: dd8e6c4396c9
Revises: 80084fc4bb32
Create Date: 2024-12-06 20:12:30.442971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8e6c4396c9'
down_revision = '80084fc4bb32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('posts', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
    #    batch_op.create_foreign_key('user_id', 'users', ['user_id'], ['id'])
    #    batch_op.drop_column('author') 
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
